application: bimsys
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
  
- url: /images
  static_dir: images
  
- url: /html
  static_dir: html
  
- url: /js
  static_dir: js
 
- url: /admin
  script: admin.py
  
- url: /.*
  script: main.py