application: groganburners
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
  
- url: /images
  static_dir: images
  
- url: /html
  static_dir: html
  
- url: /js
  static_dir: js
  
- url: /login.*
  script: login.py
  
- url: /.*
  script: bimsys.py
  
